### ISSUE TITLE
Conditional import of nuget packages 

### ISSUE THREAD

**Issue by macsux** [dotnet/dotnet-template-samples#34] opened 2018-05-01 02:28 UTC
I would like to be able to include optional nuget packages based on parameters, but can't figure out how to do that

**Comment by panmona** [comment] 2018-05-16 06:05
duplicate of #15

**Comment by sayedihashimi** [comment] 2018-05-16 21:53
Yes it is a dupe of #15, and there is a [comment](https://github.com/dotnet/dotnet-template-samples/issues/15#issuecomment-357225899) which describes how to solve the issue. I'll close this, if we need any further followup lets discuss in #15.

**Closed as completed by sayedihashimi** 2018-05-16 21:53 UTC
